[build]
  publish = "dist/lakeside-luxury-apartments/browser"
  command = "ng build && ng run lakeside-luxury-apartments:server:production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 